import pygame

LARGURA_TELA = 1280
ALTURA_TELA = 800
TITULO_JOGO = 'Magocinho'
TILESIZE = 64
TILESIZE_PLAYER = 60
FPS = 60
VELOCIDADE_JOGADOR = 3
VELOCIDADE_INIMIGO = 2

# CAMADAS
GROUND_LAYER = 1
PLAYER_LAYER = 2

ESQUERDA = -1
DIREITA = 1
BAIXO = 2
CIMA = -2

HORIZONTAL = 0
VERTICAL = 1

TIMER_DELAY_POCAO = 2000
TIMER_DELAY_COGUMELO = 2000
TIMER_DELAY_INTANGIVEL = 5000

TIMER_POCAO = pygame.USEREVENT + 1
TIMER_COGUMELO = pygame.USEREVENT + 2
TIMER_INTANGIVEL = pygame.USEREVENT + 3

tilemap = [
    'BBBBBBBBBBBBBBBBBBBB',
    'Bg.gBBg.gBBg.c.g..gB',
    'B.BggBpBg..gBBB.BB.B',
    'B.BB.B.BBBB.BBggBB.B',
    'Bg.gggg.g..gBB.BBB.B',
    'BBBcB.BB.BBg..g.c.gB',
    'Bg.gB.BB.BB.BBBBBBBB',
    'B.BBB.BB.BBgg..gBBBB',
    'Bg...g.gg..ggBBg..gB',
    'B.BBBBB.B.BB.BBBBB.B',
    'Bg.c.i.gBg..g..p..gB',
    'BBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBB'
]
