import pygame 

LARGURA_TELA = 1280
ALTURA_TELA = 720
TITULO_JOGO = 'Magocinho'
TILESIZE = 64
TILESIZE_PLAYER = 60
FPS = 60
VELOCIDADE_JOGADOR = 5
#CAMADAS

GROUND_LAYER    = 1
PLAYER_LAYER    = 2

TIMER_DELAY_POCAO = 2000
TIMER_DELAY_COGUMELO = 2000

TIMER_POCAO = pygame.USEREVENT+1
TIMER_COGUMELO = pygame.USEREVENT+2

tilemap = [
    'BBBBBBBBBBBBBBBBBBBB',
    'B...BB...BB........B',
    'B.B..B.B....BBB.BB.B',
    'B.BB.B.BBBB.BB..BB.B',
    'B...........BB.BBB.B',
    'BBB.B.BB.BB........B',
    'B...B.BB.BB.BBBBBBBB',
    'B.BBB.BB.BB.....BBBB',
    'B............BB....B',
    'B.BBBBB.B.BB.BBBBB.B',
    'B.......B..........B',
    'BBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBB'
]